build:
  commands:
    - composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
    - npm ci
    - npm run build
    
deploy:
  commands:
    - php artisan migrate --force
    - php artisan storage:link
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

